Change scripts to use absolute paths. Fix script logic and compliance with shellcheck advisories. Move i3blocks scripts to ~/.local/bin

diff --git a/.local/bin/linkhandler b/.local/bin/linkhandler
--- a/.local/bin/linkhandler
+++ b/.local/bin/linkhandler
@@ -1,4 +1,5 @@
 #!/bin/sh
+# TODO: cleanup
 
 # Fallback to browser
 [ -z "$1" ] && { "${BROWSER:?}"; exit; }
@@ -9,13 +10,10 @@ case "$1" in
 		setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
 	# sxiv
 	*png|*jpg|*jpe|*jpeg|*gif|*png?*)
-		curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -b -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
+		curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -b -a "/tmp/$(echo "$1" | sed "s/.*\///" || true)"  >/dev/null 2>&1 & ;;
 	# zathura
 	*pdf)
-		notify-send -u low 'Loading...' | curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && zathura "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
-	# fix with some podcast script
-	*mp3|*flac|*opus|*mp3?source*)
-		setsid tsp curl -LO "$1" >/dev/null 2>&1 & ;;
+		notify-send -u low 'Loading...' | curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && zathura "/tmp/$(echo "$1" | sed "s/.*\///" || true)"  >/dev/null 2>&1 & ;;
 	*)
 		if [ -f "$1" ]; then "${TERMINAL:?}" -e "${EDITOR:?} $1"
 		else setsid "${BROWSER} $1" >/dev/null 2>&1 & fi ;;
